
[build]
  command = "npm run build"
  publish = "build"

[template]
  incoming-hooks = ["Contentful"]

[template.environment]
  CONTENTFUL_CMA_TOKEN = "Contentful Content Management Token"
  REACT_APP_CTF_SPACE = "Contentful space ID"
  REACT_APP_CTF_CDA_TOKEN = "Contentful content delivery token"
  REACT_APP_CTF_CPA_TOKEN = "Contentful content preview token"